### ISSUE TITLE
[macOS] `QMPlay2` 16.04.23 fails to build on 10.6: `OpenGL2Common.hpp: error: 'GLActiveTexture' does not name a type` etc.

### ISSUE THREAD

**Issue by barracuda156** [zaps166/QMPlay2#674]
@zaps166 This looks like the last release supposed to support Qt4?
```
:info:build In file included from ./OpenGL2OldWidget.hpp:4,
:info:build                  from OpenGL2Writer.cpp:7:
:info:build ./OpenGL2Common.hpp: At global scope:
:info:build ./OpenGL2Common.hpp:44:35: error: expected ')' before '*' token
:info:build    44 |         typedef    void  (APIENTRY *GLActiveTexture)(GLenum);
:info:build       |                          ~        ^~
:info:build       |                                   )
:info:build ./OpenGL2Common.hpp:45:35: error: expected ')' before '*' token
:info:build    45 |         typedef    void  (APIENTRY *GLGenBuffers)(GLsizei, GLuint *);
:info:build       |                          ~        ^~
:info:build       |                                   )
:info:build ./OpenGL2Common.hpp:46:35: error: expected ')' before '*' token
:info:build    46 |         typedef    void  (APIENTRY *GLBindBuffer)(GLenum, GLuint);
:info:build       |                          ~        ^~
:info:build       |                                   )
:info:build ./OpenGL2Common.hpp:47:35: error: expected ')' before '*' token
:info:build    47 |         typedef    void  (APIENTRY *GLBufferData)(GLenum, GLsizeiptr, const void *, GLenum);
:info:build       |                          ~        ^~
:info:build       |                                   )
:info:build ./OpenGL2Common.hpp:48:35: error: expected ')' before '*' token
:info:build    48 |         typedef    void  (APIENTRY *GLDeleteBuffers)(GLsizei, const GLuint *);
:info:build       |                          ~        ^~
:info:build       |                                   )
:info:build ./OpenGL2Common.hpp:84:9: error: 'GLActiveTexture' does not name a type
:info:build    84 |         GLActiveTexture glActiveTexture;
:info:build       |         ^~~~~~~~~~~~~~~
:info:build ./OpenGL2Common.hpp:85:9: error: 'GLGenBuffers' does not name a type
:info:build    85 |         GLGenBuffers glGenBuffers;
:info:build       |         ^~~~~~~~~~~~
:info:build ./OpenGL2Common.hpp:86:9: error: 'GLBindBuffer' does not name a type
:info:build    86 |         GLBindBuffer glBindBuffer;
:info:build       |         ^~~~~~~~~~~~
:info:build ./OpenGL2Common.hpp:87:9: error: 'GLBufferData' does not name a type
:info:build    87 |         GLBufferData glBufferData;
:info:build       |         ^~~~~~~~~~~~
:info:build ./OpenGL2Common.hpp:88:9: error: 'GLDeleteBuffers' does not name a type
:info:build    88 |         GLDeleteBuffers glDeleteBuffers;
:info:build       |         ^~~~~~~~~~~~~~~
```
Fails both with gcc-4.2 and gcc-13.

**Comment by barracuda156** [comment]
Leaving aside FFMpeg incompatibilities with current versions, there are some other errors:
```
:info:build /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_QMPlay2/QMPlay2/work/compwrap/cxx/opt/local/bin/g++-mp-13 -c -I/opt/local/include -Os -D_GLIBCXX_USE_CXX11_ABI=0 -arch ppc -O2 -arch ppc -Wall -W -DQMPlay2_TagEditor -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/opt/local/libexec/qt4/share/mkspecs/macx-g++ -I. -Ibuild/moc -I/opt/local/libexec/qt4/Library/Frameworks/QtCore.framework/Versions/4/Headers -I/opt/local/libexec/qt4/Library/Frameworks/QtNetwork.framework/Versions/4/Headers -I/opt/local/libexec/qt4/Library/Frameworks/QtGui.framework/Versions/4/Headers -I. -I../qmplay2/headers -I/opt/local/include/taglib -I/opt/local/libexec/qt4/Library/Frameworks/QtGui.framework/Versions/4/Headers -I/opt/local/libexec/qt4/Library/Frameworks/QtNetwork.framework/Versions/4/Headers -I/opt/local/libexec/qt4/Library/Frameworks/QtCore.framework/Versions/4/Headers -I/opt/local/libexec/qt4/include -F/opt/local/libexec/qt4/Library/Frameworks -F/opt/local/libexec/qt4/lib -o build/obj/PlaylistDock.o PlaylistDock.cpp
:info:build MainWidget.cpp: In member function 'void MainWidget::createMenuBar()':
:info:build MainWidget.cpp:697:9: error: 'qt_mac_set_dock_menu' was not declared in this scope
:info:build   697 |         qt_mac_set_dock_menu(secondMenu);
:info:build       |         ^~~~~~~~~~~~~~~~~~~~
```
```
:info:build /opt/local/libexec/qt4/include/QtGui/qtransform.h:136:17: note: because 'QTransform' has user-provided 'QTransform& QTransform::operator=(const QTransform&)'
:info:build   136 |     QTransform &operator=(const QTransform &);
:info:build       |                 ^~~~~~~~
:info:build PlayClass.cpp: In member function 'void PlayClass::loadSubsFile(const QString&)':
:info:build PlayClass.cpp:327:74: error: 'QRawFont' was not declared in this scope; did you mean 'QFont'?
:info:build   327 |                                                 const QString fontName = QRawFont(fontData, 0.0).familyName();
:info:build       |                                                                          ^~~~~~~~
:info:build       |                                                                          QFont
```

**Comment by barracuda156** [comment]
`qt_mac_set_dock_menu` issue can be fixed with this: https://www.qtcentre.org/threads/13749-Problem-with-QSystemTrayIcon-on-Mac-OS
Then, disabling `OpenGL2` and `QRawFont`, I could make the app compile. Playback does not work, however: possibly, need to properly backport compatibility with modern FFMpeg.

**Comment by barracuda156** [comment]
No, I was wrong, this should still build: https://github.com/zaps166/QMPlay2/releases/tag/17.10.24
Or maybe try reverting https://github.com/zaps166/QMPlay2/commit/672f31705d8e16a9114ede0c513dc9fbd1c73348 with a newer version.

**Comment by zaps166** [comment]
Use `qt4` branch instead of tag, because it contain a bugfix. It was ~5 years ago, I don't remember, Qt4 is very old.

**Comment by zaps166** [comment]
Also macOS 10.6 is ~15 years old, many things has changed. Recently I improved OpenGL code, but it's for Qt5/Qt6. Try to declare missing types, get from newer headers somehow, maybe it'll work (or add possibly missing GL includes).

**Comment by barracuda156** [comment]
@zaps166 Thank you, I will try.

> Use qt4 branch instead of tag

I actually tried already, but turned out it still forces Qt5 (Qt5MacExtras and non-existing with Qt4 headers in a few spots), but that it fixable.

Basically I need to revert everything which breaks Qt4, but backport support for FFMpeg 4.x+. Looks doable, but perhaps already not tonight.
(Nothing reverts or cherry-picks cleanly, so while perhaps most of that will be mechanical, it likely gonna take some time.)

**Comment by zaps166** [comment]
I don't remember, but maybe I always used Qt5 for macOS builds. You can disable everything which needs `Qt5MacExtras`.

**Comment by barracuda156** [comment]
@zaps166 I actually got it working on PowerPC with Qt4. (And on Sonoma with Qt5, but that is no big deal.)

![qmplay2](https://github.com/zaps166/QMPlay2/assets/92015510/7f0a850c-296a-47a0-8f43-228f4a1b105d)

Took infinite number of rebuilds and quite substantial patching for Qt4 case, but I can play the videos now. Did not test further, need some sleep :) 

If you will have a bit of time to look through and suggest improvements, it would be awesome.
This branch has a set of patches which fix the build and apparently make the app functional: https://github.com/barracuda156/QMPlay2/tree/qt4-rev2
I had to revert a number of commits which did not build. Quite possibly reverting is suboptimal, and I just did not know how to backport the new code to Qt4. (There is also an issue with SDK: Obj C stuff is unlikely to work on older systems, and something will be missing in system headers. However aside of Obj C things can be backported, perhaps.)

Most of the problematic code is from 17.x branch (which is also present in Qt4 branch). The last 16.x release built rather neatly with minimal patching, as I mention above.

If you have Macports, this should build: https://github.com/macports/macports-ports/commit/c442cb3cb26c4fae5992d521f945f8bd100211f6

P. S. Most of multimedia players are broken on old macOS (primary issue are bugs in X11 and SDL2, which prevent them from working correctly, especially on Big-endian platforms; for instance, I could fix the build of VLC2 eventually, but colors are wrong with X11 output, while SDL is just broken). It was great to find your project – which looks a very promising option, as of now.

**Comment by barracuda156** [comment]
@zaps166 A quick update: video seems to work fine, though with 4K PowerPC machine is really struggling. Menus pretty much all work, scrolling via scrolling works, via clicking on scroll bars does not.

Youtube browsing seems dead on Qt4 version, but works on Qt5 one. (_Can we backport a fix for it?_)

Anime browsing is dead on Qt4 and missing on Qt5.

Later on the rest.

**Comment by barracuda156** [comment]
@zaps166 Could you say if this is portable to Qt4 or not? (I am not asking you to port it, to be clear. I just wanna know if it is feasible.)

For the context: I wanna try fixing YouTube and Mediabrowser, which are broken in Qt4-based version.

**Comment by zaps166** [comment]
JS syntax is obsolete in Qt4, so it'll not run the scripts properly.

**Comment by barracuda156** [comment]
@zaps166 Thank you. Maybe you have a guess why YouTube search does not work with Qt4 version?

If we know the likely cause, I can try backporting specific patches rather than blindly trying to backport everything that touched YouTube module (and then dropping some chunks, since not everything gonna build or link).

(I sort of did backport a large part of later changes, but the build erred out on YouTube.cpp, likely due to what you point out – scripts behave differently, even though some of Qt5 code can work via Qtjson4 library.)

I added support for QMPlay2 into SMtube today (in Macports, not upstream), and it works for playback of YouTube vids beautifully. But it would be more logical and user-friendly just to make internal YouTube module of QMPlay2 work (for Qt4; with Qt5 it does work perfectly as-is).

**Comment by zaps166** [comment]
This software is for Qt 5.10 and above :smile:

What "YouTube search does not work with Qt4 version" does mean? Doesn't compile? Maybe you did something wrong with porting, it uses custom networking class which uses FFmpeg + maybe you need to do something with JSON lib for Qt4.

The old code in qt4 branch is obsolete and might not be compatible with youtube anymore.

**Comment by zaps166** [comment]
The old branch is obsolete and search doesn't work because of YouTube website changes. You need to port most QMPlay2's youtube patches to make it work correctly.

**Comment by barracuda156** [comment]
@zaps166 Just for the reference, this is not abandoned, but will take some time. (No need to re-open the issue, of course. If I get it to work with YouTube, I will update here.)

**Comment by zaps166** [comment]
Ok, but I closed it because it's no longer supported.
Btw. do you want to create a PR to qt4 branch?

**Comment by barracuda156** [comment]
@zaps166 If you will accept it, sure, I will.

I will need some time though, since I am on a trip at the moment and only have arm64 laptop, where Qt4 does not even build. I gonna try sorting out back ports of some later commits in the meanwhile (which has to be done anyway prior to testing to see what can be built with Qt4 and whether that gonna improve the app), and once I am back to my PowerPC and x86 hardware, gonna test everything.
It will be nice to have some online capabilities working, though at the moment I have no idea if that could work in principle with the old Qt4. But I will try to fix at least something. `QMPlay2` is a great app, and as of now, I think, the only player with GUI in Macports which works perfectly for video-playback on PowerPC. (I kinda have WIP to fix VLC2, but I could only make X11 backend to work so far, and that one has some endianness?-related bug, which I had no time to track down.)

**Comment by RJVB** [comment]
@barracuda156 was it you who thought he might use my patches to build Qt5 in X11/XCB mode to port Qt5 to PowerPC?
 
QMPlay2 is currently Qt 5.10+ as pointed out above, but you may have seen that I have a patch to make it build against Qt 5.9 . If ever there was a Qt5 version that supported the platforms you are targetting you will probably do good to get a more current QMPlay2 version to build against that Qt5 version.
That could be a tall order too, but you'd mostly be implementing relatively simple glue/conditional code or algorithms rather than trying to understand the inner QMPlay2 workings.

**Comment by barracuda156** [comment]
@RJVB Yeah, it was me, we discussed it briefly here: https://trac.macports.org/ticket/69051
I did not have time to return to that so far. (Well, it demotivates also when you spend hours on something and it keeps getting nowhere. Qt upstream did a “good job” breaking everything in a versatile way, LOL.)

**Comment by RJVB** [comment]
On Monday March 18 2024 14:27:26 Sergey Fedorov wrote:
> Well, it demotivates also when you spend hours on something and it keeps getting nowhere. 

Would that be a rabbit or a black hole? :)
I had one recently where I spent a considerable amount of time on getting a newer webkit2-gtk to build, only to find out that it made my system KP.

> Qt upstream did a “good job” breaking everything in a versatile way, LOL.)

That's why I'm really not looking forward to the day I cave and upgrade my Mac, after which I'll "have" to upgrade my Qt5 port too...

**Comment by barracuda156** [comment]
@catap has been doing some work to fix `webkit2-gtk`, AFAIK. Not sure what is the current state of the issue.

**Comment by catap** [comment]
On Mon, 18 Mar 2024 23:53:50 +0100,
Sergey Fedorov wrote:
> 
> @catap has been doing some work to fix `webkit2-gtk`, AFAIK. Not sure what is the current state of the issue.
> 

I buuild it, but it crashes on any attempt to use it.

-- 
wbr, Kirill

**Comment by RJVB** [comment]
>I buuild it, but it crashes on any attempt to use it.

What version? The app crashing is better than it crashing the entire machine (the 2nd time it didn't even KP immediately, but the morning after when I had almost forgotten that I had used it once...)

(And FWIW, I built the same version on Linux, where it runs fine with its own MiniBrowser but just "beachballs" in Epiphany, so maybe I need to upgrade that one too.)

**Comment by RJVB** [comment]
>I mean crashing an example from webkit

That's the thing: the MiniBrowser *appears* to work in my build (except for `about:gpu` which is probably because I had to disable the entire WEB_GL feature), but it then causes an instability somewhere that leads to a KP ultimately. It reminded me of how I used to have those with earlier OS X versions when I was still actively doing OpenGL programming myself.

@mascguy is also working on updating webkit2-gtk-devel; my version was based on his, hence:
https://github.com/mascguy/macports-ports/pull/1

A few weeks back I read a discussion on the LLVM discourse pages that mentioned how clang versions before 17 had broken support for C++20 that could also lead to miscompiles. WK 2.40 requires that standard but I had been using clang-12 and indeed encountered a number of seemingly illogical build failures (that I avoided by disabling WEBGL). According to that LLVM discussion you'd have to use GCC12+ or clang-17 (which can't even build itself at the moment; probably because it needs to have a more recent libc++ runtime that we currently have in MacPorts). I haven't yet had the courage to try again now that I have GCC12 because my experience with the newer WK version on Linux shows too little gain w.r.t. 2.28.2 (but a *lot* more hunger for resources).

**Comment by barracuda156** [comment]
@RJVB I got an idea: build the same old version (which supports Qt4) with Qt5 on Sonoma and see if I can fix YouTube there. Right now I could build it (commenting out a single chunk of unrelated code in audio filters), and YouTube search is broken. Which means that it _might_ be not due to Qt4.

**Comment by RJVB** [comment]
YouTube functionality has been overhauled quite a bit the past few years, to keep up with upstream changes. Which script does the code you're testing use, `youtube-dl` or `yt-dlp`? The former is no longer maintained AFAIK, the latter is.

**Comment by barracuda156** [comment]
@RJVB I have fixed playback now. There are two relatively minor issues: get rid of auto downloading yt-dlp (it calls non-existing python3 and fails, expectedly) in favor of a normal external dependency (MacPorts version works correctly) and fix HD video streaming, which was broken recently by YouTube engine.
The latter has been fixed in QMPlay2 around 21.x versions, but related commits are huge and require sequential rebase of lots of changes (nothing backports cleanly).
Do you know by change what is the minimal change to fix that? The problem is known and affects multiple apps (yewtube, for example).

**Comment by RJVB** [comment]
On Tuesday November 19 2024 04:48:11 Sergey Fedorov wrote:
>@RJVB I have fixed playback now. There are two relatively minor issues: get rid of auto downloading yt-dlp (it calls non-existing python3 and fails, expectedly)

In my port:QMplay2 you'll find a patch that unpacks yt-dlp and then (probably :) ) calls the python interpreter with a script argument. That saves a nice bit of time on each invocation, too.

>Do you know by change what is the minimal change to fix that? The problem is known and affects multiple apps (yewtube, for example).

No, I'm sorry, I was never involved with any of that central stuff. For me, QMPlay2 just uses yt-dlp to obtain the video and audio streams of choice and then hands them off to FFmpeg to get the corresponding frames to display and send to the audio subsystem. I also only use 720P myself, which I noticed isn't even considered HD anymore these days...

**Comment by RJVB** [comment]
On Tuesday November 19 2024 09:36:17 Sergey Fedorov wrote:
>@RJVB If you referred to this patch https://github.com/RJVB/macstrop/commit/1c6e2b1d6b75a2a7f27d8cd73bd91a054991bbb3 then it probably won’t work since `QStandardPaths` are Qt5-specific,

True. I wasn't suggesting you'd use it directly because it probably won't apply anyway. And the use of `findExecutable` is probably the easiest to drop for personal use if you take care to invoke only external applications that are on your path.
 
>>I honestly think that a choice to use external `yt-dlp` is a legit improvement independent of my specific issue, and should arguably be introduced in upstream code.

Agreed, but the author doesn't seem to find it very important or useful, and on a modern, powerful machine it indeed may not be. Not even for occasional use on an older/slower machine when network response times and parsing of json data are probably equal bottlenecks.

**Comment by barracuda156** [comment]
@RJVB BTW I found an exact commit which fixes HD streaming: https://github.com/zaps166/QMPlay2/commit/2f9281bb1026afd55650f4c33fdd3f3b91deee85

Unfortunately, it does not apply, and nothing similar exists in the older code, so it will pull an unknown amount of backporting.

**Comment by barracuda156** [comment]
@RJVB I guess this is why I gave up last time: YT-related code was rewritten multiple times in huge all-in commits, quick hackish attempt to backport those directly either failed to compile or I just got tired of shuffling the code without any idea if it will ever work. Now I know for sure that it can work, without bells & whistles of Qt5, with relatively minimal fixes. So at least it does not feel totally pointless.
However, the last remaining part turns a bit nightmarish, since this is needed (possibly partly, but it is unclear): https://github.com/zaps166/QMPlay2/commit/f0c0ca05d837942eaadf935ce19ce142ba2dd518
And this commit with a rather obscure changes in some parts does not relate to the older code.

**Comment by barracuda156** [comment]
>  Is there an equivalent file in the older code for each of the YT-related files in the current code? (.cpp files of course)

@RJVB Yes, though I am not sure if it stayed in pure C++. MediaBrowser module was apparently redone in JS.
I could try replacing the module and see how badly in fails. As long as it does not require QML and JS, that indeed may work. Qt5 version of Json is kinda supported via `json4` library, so this is not a stopper.

**Comment by RJVB** [comment]
On Tuesday November 19 2024 13:46:38 Sergey Fedorov wrote:

>MediaBrowser module was apparently redone in JS.

I'm not certain this is used for YouTube at all? AFAICT it isn't in the version I'm still on (from last June; I can't recall having seen a notification about an update since).

I was really only talking about the files labelled YouTube in src/modules/Extensions and src/qmplay2 ; they don't include either of the MediaBrowser headers (again, in the code I have checked out) so shouldn't have hard dependencies on that feature.

**Comment by barracuda156** [comment]
Yeah, I don’t think it depends on MediaBrowser. Pretty much all commits dealing with YouTube touched `YouTube.*`, `YouTubeDL.*`, `Extensions.*` and `Functions.*` files. Perhaps nothing else. `Extensions.*` are probably common to something else, but then I could also just disable modules which are both broken and unneeded. I just need video, audio and streaming/downloading of these.

**Comment by barracuda156** [comment]
Honestly it looks like `GLActiveTexture` is misplaced. It is used here when `OPENGL_ES2` is _not_ defined, but it is a part of Apple iOS API: https://developer.apple.com/documentation/opengles/glactivetexture(_:)
It is likely absent in macOS SDK, so it should not be found.

**Comment by barracuda156** [comment]
@RJVB Hmm, interesting. Thank you.
Perhaps the right headers were not being pulled. Something existing since 10.0 will verily be present in 10.6, even early developer builds.

**Comment by RJVB** [comment]
On Saturday November 23 2024 05:45:39 Sergey Fedorov wrote:

>Perhaps the right headers were not being pulled. 

Well, yes, you'd need to pull Apple's OpenGL headers. IIRC cross-platform code including OpenGL headers usually has an #ifdef section for that.

@zaps166: how much of an effort, overhead and benefit would it be to rewrite the OpenGL code so it uses something like libepoxy or glew?
