### ISSUE TITLE
(openSUSE 13.1 + Qt5) build error: no match for 'operator&gt;'

### ISSUE THREAD

**Issue by DAP-DarkneSS** [zaps166/QMPlay2#7]
[   57s] cd src/ &amp;&amp; ( test -e Makefile || /usr/bin/qmake-qt5 /home/abuild/rpmbuild/BUILD/QMPlay2-src-15.12.06/src/src.pro -o Makefile ) &amp;&amp; make -f Makefile 
[   57s] make[1]: Entering directory `/home/abuild/rpmbuild/BUILD/QMPlay2-src-15.12.06/src'
[   57s] cd qmplay2/ &amp;&amp; ( test -e Makefile || /usr/bin/qmake-qt5 /home/abuild/rpmbuild/BUILD/QMPlay2-src-15.12.06/src/qmplay2/qmplay2.pro -o Makefile ) &amp;&amp; make -f Makefile 
[   57s] make[2]: Entering directory `/home/abuild/rpmbuild/BUILD/QMPlay2-src-15.12.06/src/qmplay2'
[   57s] g++ -c -pipe -O2 -Wall -W -D_REENTRANT -fPIC -D__STDC_CONSTANT_MACROS -DQT_NO_DEBUG -DQT_PLUGIN -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/include -I/usr/lib64/qt5/mkspecs/linux-g++ -I. -I. -Iheaders -I/usr/include/ffmpeg -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/fribidi -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -Ibuild/moc -o build/obj/QMPlay2Core.o QMPlay2Core.cpp
[   57s] g++ -c -pipe -O2 -Wall -W -D_REENTRANT -fPIC -D__STDC_CONSTANT_MACROS -DQT_NO_DEBUG -DQT_PLUGIN -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/include -I/usr/lib64/qt5/mkspecs/linux-g++ -I. -I. -Iheaders -I/usr/include/ffmpeg -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/fribidi -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -Ibuild/moc -o build/obj/Functions.o Functions.cpp
[   57s] g++ -c -pipe -O2 -Wall -W -D_REENTRANT -fPIC -D__STDC_CONSTANT_MACROS -DQT_NO_DEBUG -DQT_PLUGIN -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/include -I/usr/lib64/qt5/mkspecs/linux-g++ -I. -I. -Iheaders -I/usr/include/ffmpeg -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/fribidi -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -Ibuild/moc -o build/obj/Settings.o Settings.cpp
[   58s] In file included from headers/Settings.hpp:4:0,
[   58s]                  from Settings.cpp:1:
[   58s] headers/QMPlay2Core.hpp: In member function 'bool QMPlay2CoreClass::isWorking()':
[   58s] headers/QMPlay2Core.hpp:107:18: error: no match for 'operator&gt;' (operand types are 'QAtomicInt' and 'int')
[   58s]    return working &gt; 0;
[   58s]                   ^
[   58s] headers/QMPlay2Core.hpp:107:18: note: candidates are:
[   58s] In file included from /usr/include/qt5/QtCore/qdatastream.h:47:0,
[   58s]                  from /usr/include/qt5/QtCore/qstringlist.h:46,
[   58s]                  from /usr/include/qt5/QtGui/qcolor.h:47,
[   58s]                  from /usr/include/qt5/QtGui/qpixmap.h:46,
[   58s]                  from /usr/include/qt5/QtGui/qicon.h:48,
[   58s]                  from /usr/include/qt5/QtGui/QIcon:1,
[   58s]                  from headers/QMPlay2Core.hpp:12,
[   58s]                  from headers/Settings.hpp:4,
[   58s]                  from Settings.cpp:1:
[   58s] /usr/include/qt5/QtCore/qpair.h:84:24: note: template&lt;class T1, class T2&gt; bool operator&gt;(const QPair&lt;T, U&gt;&amp;, const QPair&lt;T, U&gt;&amp;)
[   58s]  Q_INLINE_TEMPLATE bool operator&gt;(const QPair&lt;T1, T2&gt; &amp;p1, const QPair&lt;T1, T2&gt; &amp;p2)
[   58s]                         ^
[   58s] /usr/include/qt5/QtCore/qpair.h:84:24: note:   template argument deduction/substitution failed:
[   58s] In file included from headers/Settings.hpp:4:0,
[   58s]                  from Settings.cpp:1:
[   58s] headers/QMPlay2Core.hpp:107:20: note:   'QAtomicInt' is not derived from 'const QPair&lt;T, U&gt;'
[   58s]    return working &gt; 0;
[   58s]                     ^
[   58s] In file included from /usr/include/qt5/QtCore/qobject.h:49:0,
[   58s]                  from /usr/include/qt5/QtCore/QObject:1,
[   58s]                  from headers/QMPlay2Core.hpp:11,
[   58s]                  from headers/Settings.hpp:4,
[   58s]                  from Settings.cpp:1:
[   58s] /usr/include/qt5/QtCore/qstring.h:1331:13: note: bool operator&gt;(const QStringRef&amp;, const QStringRef&amp;)
[   58s]  inline bool operator&gt;(const QStringRef &amp;s1, const QStringRef &amp;s2)
[   58s]              ^
[   58s] /usr/include/qt5/QtCore/qstring.h:1331:13: note:   no known conversion for argument 1 from 'QAtomicInt' to 'const QStringRef&amp;'
[   58s] /usr/include/qt5/QtCore/qstring.h:1044:32: note: bool operator&gt;(const char*, QLatin1String)
[   58s]  inline QT_ASCII_CAST_WARN bool operator&gt;(const char *s1, QLatin1String s2)
[   58s]                                 ^
[   58s] /usr/include/qt5/QtCore/qstring.h:1044:32: note:   no known conversion for argument 1 from 'QAtomicInt' to 'const char*'
[   58s] /usr/include/qt5/QtCore/qstring.h:991:13: note: bool operator&gt;(QLatin1String, QLatin1String)
[   58s]  inline bool operator&gt;(QLatin1String s1, QLatin1String s2)
[   58s]              ^
[   58s] /usr/include/qt5/QtCore/qstring.h:991:13: note:   no known conversion for argument 1 from 'QAtomicInt' to 'QLatin1String'
[   58s] /usr/include/qt5/QtCore/qstring.h:1360:32: note: bool operator&gt;(const char*, const QStringRef&amp;)
[   58s]  inline QT_ASCII_CAST_WARN bool operator&gt;(const char *s1, const QStringRef &amp;s2)
[   58s]                                 ^
[   58s] /usr/include/qt5/QtCore/qstring.h:1360:32: note:   no known conversion for argument 1 from 'QAtomicInt' to 'const char*'
[   58s] /usr/include/qt5/QtCore/qstring.h:1031:32: note: bool operator&gt;(const char*, const QString&amp;)
[   58s]  inline QT_ASCII_CAST_WARN bool operator&gt;(const char *s1, const QString &amp;s2)
[   58s]                                 ^
[   58s] /usr/include/qt5/QtCore/qstring.h:1031:32: note:   no known conversion for argument 1 from 'QAtomicInt' to 'const char*'
[   58s] In file included from /usr/include/qt5/QtCore/qstring.h:46:0,
[   58s]                  from /usr/include/qt5/QtCore/qobject.h:49,
[   58s]                  from /usr/include/qt5/QtCore/QObject:1,
[   58s]                  from headers/QMPlay2Core.hpp:11,
[   58s]                  from headers/Settings.hpp:4,
[   58s]                  from Settings.cpp:1:
[   58s] /usr/include/qt5/QtCore/qbytearray.h:552:13: note: bool operator&gt;(const char*, const QByteArray&amp;)
[   58s]  inline bool operator&gt;(const char *a1, const QByteArray &amp;a2)
[   58s]              ^
[   58s] /usr/include/qt5/QtCore/qbytearray.h:552:13: note:   no known conversion for argument 1 from 'QAtomicInt' to 'const char*'
[   58s] /usr/include/qt5/QtCore/qbytearray.h:550:13: note: bool operator&gt;(const QByteArray&amp;, const char*)
[   58s]  inline bool operator&gt;(const QByteArray &amp;a1, const char *a2)
[   58s]              ^
[   58s] /usr/include/qt5/QtCore/qbytearray.h:550:13: note:   no known conversion for argument 1 from 'QAtomicInt' to 'const QByteArray&amp;'
[   58s] /usr/include/qt5/QtCore/qbytearray.h:548:13: note: bool operator&gt;(const QByteArray&amp;, const QByteArray&amp;)
[   58s]  inline bool operator&gt;(const QByteArray &amp;a1, const QByteArray &amp;a2)
[   58s]              ^
[   58s] /usr/include/qt5/QtCore/qbytearray.h:548:13: note:   no known conversion for argument 1 from 'QAtomicInt' to 'const QByteArray&amp;'
[   58s] In file included from /usr/include/qt5/QtCore/qstring.h:45:0,
[   58s]                  from /usr/include/qt5/QtCore/qobject.h:49,
[   58s]                  from /usr/include/qt5/QtCore/QObject:1,
[   58s]                  from headers/QMPlay2Core.hpp:11,
[   58s]                  from headers/Settings.hpp:4,
[   58s]                  from Settings.cpp:1:
[   58s] /usr/include/qt5/QtCore/qchar.h:518:13: note: bool operator&gt;(QChar, QChar)
[   58s]  inline bool operator&gt;(QChar c1, QChar c2) { return c1.unicode() &gt; c2.unicode(); }
[   58s]              ^
[   58s] /usr/include/qt5/QtCore/qchar.h:518:13: note:   no known conversion for argument 1 from 'QAtomicInt' to 'QChar'
[   58s] In file included from QMPlay2Core.cpp:1:0:
[   58s] headers/QMPlay2Core.hpp: In member function 'bool QMPlay2CoreClass::isWorking()':
[   58s] headers/QMPlay2Core.hpp:107:18: error: no match for 'operator&gt;' (operand types are 'QAtomicInt' and 'int')
[   58s]    return working &gt; 0;
[   58s]                   ^
[   58s] headers/QMPlay2Core.hpp:107:18: note: candidates are:
[   58s] In file included from /usr/include/qt5/QtCore/qdatastream.h:47:0,
[   58s]                  from /usr/include/qt5/QtCore/qstringlist.h:46,
[   58s]                  from /usr/include/qt5/QtGui/qcolor.h:47,
[   58s]                  from /usr/include/qt5/QtGui/qpixmap.h:46,
[   58s]                  from /usr/include/qt5/QtGui/qicon.h:48,
[   58s]                  from /usr/include/qt5/QtGui/QIcon:1,
[   58s]                  from headers/QMPlay2Core.hpp:12,
[   58s]                  from QMPlay2Core.cpp:1:
[   58s] /usr/include/qt5/QtCore/qpair.h:84:24: note: template&lt;class T1, class T2&gt; bool operator&gt;(const QPair&lt;T, U&gt;&amp;, const QPair&lt;T, U&gt;&amp;)
[   58s]  Q_INLINE_TEMPLATE bool operator&gt;(const QPair&lt;T1, T2&gt; &amp;p1, const QPair&lt;T1, T2&gt; &amp;p2)
[   58s]                         ^
[   58s] /usr/include/qt5/QtCore/qpair.h:84:24: note:   template argument deduction/substitution failed:
[   58s] In file included from QMPlay2Core.cpp:1:0:
[   58s] headers/QMPlay2Core.hpp:107:20: note:   'QAtomicInt' is not derived from 'const QPair&lt;T, U&gt;'
[   58s]    return working &gt; 0;
[   58s]                     ^
[   58s] In file included from /usr/include/qt5/QtCore/qobject.h:49:0,
[   58s]                  from /usr/include/qt5/QtCore/QObject:1,
[   58s]                  from headers/QMPlay2Core.hpp:11,
[   58s]                  from QMPlay2Core.cpp:1:
[   58s] /usr/include/qt5/QtCore/qstring.h:1331:13: note: bool operator&gt;(const QStringRef&amp;, const QStringRef&amp;)
[   58s]  inline bool operator&gt;(const QStringRef &amp;s1, const QStringRef &amp;s2)
[   58s]              ^
[   58s] /usr/include/qt5/QtCore/qstring.h:1331:13: note:   no known conversion for argument 1 from 'QAtomicInt' to 'const QStringRef&amp;'
[   58s] /usr/include/qt5/QtCore/qstring.h:1044:32: note: bool operator&gt;(const char*, QLatin1String)
[   58s]  inline QT_ASCII_CAST_WARN bool operator&gt;(const char *s1, QLatin1String s2)
[   58s]                                 ^
[   58s] /usr/include/qt5/QtCore/qstring.h:1044:32: note:   no known conversion for argument 1 from 'QAtomicInt' to 'const char*'
[   58s] /usr/include/qt5/QtCore/qstring.h:991:13: note: bool operator&gt;(QLatin1String, QLatin1String)
[   58s]  inline bool operator&gt;(QLatin1String s1, QLatin1String s2)
[   58s]              ^
[   58s] /usr/include/qt5/QtCore/qstring.h:991:13: note:   no known conversion for argument 1 from 'QAtomicInt' to 'QLatin1String'
[   58s] /usr/include/qt5/QtCore/qstring.h:1360:32: note: bool operator&gt;(const char*, const QStringRef&amp;)
[   58s]  inline QT_ASCII_CAST_WARN bool operator&gt;(const char *s1, const QStringRef &amp;s2)
[   58s]                                 ^
[   58s] /usr/include/qt5/QtCore/qstring.h:1360:32: note:   no known conversion for argument 1 from 'QAtomicInt' to 'const char*'
[   58s] /usr/include/qt5/QtCore/qstring.h:1031:32: note: bool operator&gt;(const char*, const QString&amp;)
[   58s]  inline QT_ASCII_CAST_WARN bool operator&gt;(const char *s1, const QString &amp;s2)
[   58s]                                 ^
[   58s] /usr/include/qt5/QtCore/qstring.h:1031:32: note:   no known conversion for argument 1 from 'QAtomicInt' to 'const char*'
[   58s] In file included from /usr/include/qt5/QtCore/qstring.h:46:0,
[   58s]                  from /usr/include/qt5/QtCore/qobject.h:49,
[   58s]                  from /usr/include/qt5/QtCore/QObject:1,
[   58s]                  from headers/QMPlay2Core.hpp:11,
[   58s]                  from QMPlay2Core.cpp:1:
[   58s] /usr/include/qt5/QtCore/qbytearray.h:552:13: note: bool operator&gt;(const char*, const QByteArray&amp;)
[   58s]  inline bool operator&gt;(const char *a1, const QByteArray &amp;a2)
[   58s]              ^
[   58s] /usr/include/qt5/QtCore/qbytearray.h:552:13: note:   no known conversion for argument 1 from 'QAtomicInt' to 'const char*'
[   58s] /usr/include/qt5/QtCore/qbytearray.h:550:13: note: bool operator&gt;(const QByteArray&amp;, const char*)
[   58s]  inline bool operator&gt;(const QByteArray &amp;a1, const char *a2)
[   58s]              ^
[   58s] /usr/include/qt5/QtCore/qbytearray.h:550:13: note:   no known conversion for argument 1 from 'QAtomicInt' to 'const QByteArray&amp;'
[   58s] /usr/include/qt5/QtCore/qbytearray.h:548:13: note: bool operator&gt;(const QByteArray&amp;, const QByteArray&amp;)
[   58s]  inline bool operator&gt;(const QByteArray &amp;a1, const QByteArray &amp;a2)
[   58s]              ^
[   58s] /usr/include/qt5/QtCore/qbytearray.h:548:13: note:   no known conversion for argument 1 from 'QAtomicInt' to 'const QByteArray&amp;'
[   58s] In file included from /usr/include/qt5/QtCore/qstring.h:45:0,
[   58s]                  from /usr/include/qt5/QtCore/qobject.h:49,
[   58s]                  from /usr/include/qt5/QtCore/QObject:1,
[   58s]                  from headers/QMPlay2Core.hpp:11,
[   58s]                  from QMPlay2Core.cpp:1:
[   58s] /usr/include/qt5/QtCore/qchar.h:518:13: note: bool operator&gt;(QChar, QChar)
[   58s]  inline bool operator&gt;(QChar c1, QChar c2) { return c1.unicode() &gt; c2.unicode(); }
[   58s]              ^
[   58s] /usr/include/qt5/QtCore/qchar.h:518:13: note:   no known conversion for argument 1 from 'QAtomicInt' to 'QChar'
[   58s] In file included from headers/Settings.hpp:4:0,
[   58s]                  from headers/Module.hpp:8,
[   58s]                  from headers/ModuleCommon.hpp:4,
[   58s]                  from headers/QMPlay2Extensions.hpp:5,
[   58s]                  from Functions.cpp:3:
[   58s] headers/QMPlay2Core.hpp: In member function 'bool QMPlay2CoreClass::isWorking()':
[   58s] headers/QMPlay2Core.hpp:107:18: error: no match for 'operator&gt;' (operand types are 'QAtomicInt' and 'int')
[   58s]    return working &gt; 0;
[   58s]                   ^
[   58s] headers/QMPlay2Core.hpp:107:18: note: candidates are:
[   58s] In file included from /usr/include/qt5/QtCore/qhash.h:48:0,
[   58s]                  from /usr/include/qt5/QtCore/qsharedpointer_impl.h:66,
[   58s]                  from /usr/include/qt5/QtCore/qsharedpointer.h:50,
[   58s]                  from /usr/include/qt5/QtCore/QSharedPointer:1,
[   58s]                  from headers/IOController.hpp:13,
[   58s]                  from headers/Functions.hpp:4,
[   58s]                  from Functions.cpp:1:
[   58s] /usr/include/qt5/QtCore/qpair.h:84:24: note: template&lt;class T1, class T2&gt; bool operator&gt;(const QPair&lt;T, U&gt;&amp;, const QPair&lt;T, U&gt;&amp;)
[   58s]  Q_INLINE_TEMPLATE bool operator&gt;(const QPair&lt;T1, T2&gt; &amp;p1, const QPair&lt;T1, T2&gt; &amp;p2)
[   58s]                         ^
[   58s] /usr/include/qt5/QtCore/qpair.h:84:24: note:   template argument deduction/substitution failed:
[   58s] In file included from headers/Settings.hpp:4:0,
[   58s]                  from headers/Module.hpp:8,
[   58s]                  from headers/ModuleCommon.hpp:4,
[   58s]                  from headers/QMPlay2Extensions.hpp:5,
[   58s]                  from Functions.cpp:3:
[   58s] headers/QMPlay2Core.hpp:107:20: note:   'QAtomicInt' is not derived from 'const QPair&lt;T, U&gt;'
[   58s]    return working &gt; 0;
[   58s]                     ^
[   58s] In file included from /usr/include/qt5/QtCore/qobject.h:49:0,
[   58s]                  from /usr/include/qt5/QtCore/qsharedpointer_impl.h:65,
[   58s]                  from /usr/include/qt5/QtCore/qsharedpointer.h:50,
[   58s]                  from /usr/include/qt5/QtCore/QSharedPointer:1,
[   58s]                  from headers/IOController.hpp:13,
[   58s]                  from headers/Functions.hpp:4,
[   58s]                  from Functions.cpp:1:
[   58s] /usr/include/qt5/QtCore/qstring.h:1331:13: note: bool operator&gt;(const QStringRef&amp;, const QStringRef&amp;)
[   58s]  inline bool operator&gt;(const QStringRef &amp;s1, const QStringRef &amp;s2)
[   58s]              ^
[   58s] /usr/include/qt5/QtCore/qstring.h:1331:13: note:   no known conversion for argument 1 from 'QAtomicInt' to 'const QStringRef&amp;'
[   58s] /usr/include/qt5/QtCore/qstring.h:1044:32: note: bool operator&gt;(const char*, QLatin1String)
[   58s]  inline QT_ASCII_CAST_WARN bool operator&gt;(const char *s1, QLatin1String s2)
[   58s]                                 ^
[   58s] /usr/include/qt5/QtCore/qstring.h:1044:32: note:   no known conversion for argument 1 from 'QAtomicInt' to 'const char*'
[   58s] /usr/include/qt5/QtCore/qstring.h:991:13: note: bool operator&gt;(QLatin1String, QLatin1String)
[   58s]  inline bool operator&gt;(QLatin1String s1, QLatin1String s2)
[   58s]              ^
[   58s] /usr/include/qt5/QtCore/qstring.h:991:13: note:   no known conversion for argument 1 from 'QAtomicInt' to 'QLatin1String'
[   58s] /usr/include/qt5/QtCore/qstring.h:1360:32: note: bool operator&gt;(const char*, const QStringRef&amp;)
[   58s]  inline QT_ASCII_CAST_WARN bool operator&gt;(const char *s1, const QStringRef &amp;s2)
[   58s]                                 ^
[   58s] /usr/include/qt5/QtCore/qstring.h:1360:32: note:   no known conversion for argument 1 from 'QAtomicInt' to 'const char*'
[   58s] /usr/include/qt5/QtCore/qstring.h:1031:32: note: bool operator&gt;(const char*, const QString&amp;)
[   58s]  inline QT_ASCII_CAST_WARN bool operator&gt;(const char *s1, const QString &amp;s2)
[   58s]                                 ^
[   58s] /usr/include/qt5/QtCore/qstring.h:1031:32: note:   no known conversion for argument 1 from 'QAtomicInt' to 'const char*'
[   58s] In file included from /usr/include/qt5/QtCore/qstring.h:46:0,
[   58s]                  from /usr/include/qt5/QtCore/qobject.h:49,
[   58s]                  from /usr/include/qt5/QtCore/qsharedpointer_impl.h:65,
[   58s]                  from /usr/include/qt5/QtCore/qsharedpointer.h:50,
[   58s]                  from /usr/include/qt5/QtCore/QSharedPointer:1,
[   58s]                  from headers/IOController.hpp:13,
[   58s]                  from headers/Functions.hpp:4,
[   58s]                  from Functions.cpp:1:
[   58s] /usr/include/qt5/QtCore/qbytearray.h:552:13: note: bool operator&gt;(const char*, const QByteArray&amp;)
[   58s]  inline bool operator&gt;(const char *a1, const QByteArray &amp;a2)
[   58s]              ^
[   58s] /usr/include/qt5/QtCore/qbytearray.h:552:13: note:   no known conversion for argument 1 from 'QAtomicInt' to 'const char*'
[   58s] /usr/include/qt5/QtCore/qbytearray.h:550:13: note: bool operator&gt;(const QByteArray&amp;, const char*)
[   58s]  inline bool operator&gt;(const QByteArray &amp;a1, const char *a2)
[   58s]              ^
[   58s] /usr/include/qt5/QtCore/qbytearray.h:550:13: note:   no known conversion for argument 1 from 'QAtomicInt' to 'const QByteArray&amp;'
[   58s] /usr/include/qt5/QtCore/qbytearray.h:548:13: note: bool operator&gt;(const QByteArray&amp;, const QByteArray&amp;)
[   58s]  inline bool operator&gt;(const QByteArray &amp;a1, const QByteArray &amp;a2)
[   58s]              ^
[   58s] /usr/include/qt5/QtCore/qbytearray.h:548:13: note:   no known conversion for argument 1 from 'QAtomicInt' to 'const QByteArray&amp;'
[   58s] In file included from /usr/include/qt5/QtCore/qstring.h:45:0,
[   58s]                  from /usr/include/qt5/QtCore/qobject.h:49,
[   58s]                  from /usr/include/qt5/QtCore/qsharedpointer_impl.h:65,
[   58s]                  from /usr/include/qt5/QtCore/qsharedpointer.h:50,
[   58s]                  from /usr/include/qt5/QtCore/QSharedPointer:1,
[   58s]                  from headers/IOController.hpp:13,
[   58s]                  from headers/Functions.hpp:4,
[   58s]                  from Functions.cpp:1:
[   58s] /usr/include/qt5/QtCore/qchar.h:518:13: note: bool operator&gt;(QChar, QChar)
[   58s]  inline bool operator&gt;(QChar c1, QChar c2) { return c1.unicode() &gt; c2.unicode(); }
[   58s]              ^
[   58s] /usr/include/qt5/QtCore/qchar.h:518:13: note:   no known conversion for argument 1 from 'QAtomicInt' to 'QChar'
[   58s] make[2]: *** [build/obj/Settings.o] Error 1
[   58s] make[2]: *** Waiting for unfinished jobs....
[   58s] make[2]: *** [build/obj/QMPlay2Core.o] Error 1
[   58s] make[2]: *** [build/obj/Functions.o] Error 1
[   58s] make[2]: Leaving directory `/home/abuild/rpmbuild/BUILD/QMPlay2-src-15.12.06/src/qmplay2'
[   58s] make[1]: *** [sub-qmplay2-make_first-ordered] Error 2
[   58s] make[1]: Leaving directory `/home/abuild/rpmbuild/BUILD/QMPlay2-src-15.12.06/src'
[   58s] make: *** [sub-src-make_first] Error 2
[   58s] 
[   58s] real	0m1.391s
[   58s] user	0m2.676s
[   58s] sys	0m0.248s

**Comment by zaps166** [comment]
openSUSE 13.1 uses old Qt 5.1. You should use Qt4 for QMPlay2, because it is still better. I don't know how QMPlay2 will works in Qt 5.1
But I can fix it :D

**Comment by zaps166** [comment]
Please try now with 86ad547

**Comment by DAP-DarkneSS** [comment]
Thank you very much! If Qt 5.1 isn't OK build configuration should fail imho.

**Comment by zaps166** [comment]
For me Qt 5.5.1 is not OK. I'm waiting for Qt 5.6.
I don't know if 5.1 is OK or not - you must try and compare to Qt 4.8. I don't remember Qt 5.1, but you may expect crashes or slowdowns or that something won't work :D

**Comment by DAP-DarkneSS** [comment]
[  181s] g++ -c -pipe -O2 -Wall -W -D_REENTRANT -fPIE -DX11_EXTRAS -DQMPlay2_TagEditor -DQT_NO_DEBUG -DQT_X11EXTRAS_LIB -DQT_WIDGETS_LIB -DQT_NETWORK_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/include -I/usr/lib64/qt5/mkspecs/linux-g++ -I. -I. -I../qmplay2/headers -I/usr/include/taglib -I/usr/include/qt5 -I/usr/include/qt5/QtX11Extras -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -Ibuild/moc -o build/obj/AudioThr.o AudioThr.cpp
[  182s] VideoThr.cpp: In member function 'void VideoThr::write_slot(const QByteArray&amp;)':
[  182s] VideoThr.cpp:486:7: error: 'isPlatformX11' is not a member of 'QX11Info'
[  182s]   if ( QX11Info::isPlatformX11() )
[  182s]        ^
[  182s] g++ -c -pipe -O2 -Wall -W -D_REENTRANT -fPIE -DX11_EXTRAS -DQMPlay2_TagEditor -DQT_NO_DEBUG -DQT_X11EXTRAS_LIB -DQT_WIDGETS_LIB -DQT_NETWORK_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/include -I/usr/lib64/qt5/mkspecs/linux-g++ -I. -I. -I../qmplay2/headers -I/usr/include/taglib -I/usr/include/qt5 -I/usr/include/qt5/QtX11Extras -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -Ibuild/moc -o build/obj/SettingsWidget.o SettingsWidget.cpp
[  182s] make[2]: *** [build/obj/VideoThr.o] Error 1
[  182s] make[2]: *** Waiting for unfinished jobs....
[  189s] make[2]: Leaving directory `/home/abuild/rpmbuild/BUILD/QMPlay2-src-15.12.06/src/gui'
[  189s] make[1]: *** [sub-gui-make_first-ordered] Error 2
[  189s] make[1]: Leaving directory `/home/abuild/rpmbuild/BUILD/QMPlay2-src-15.12.06/src'
[  189s] make: *** [sub-src-make_first] Error 2
Should I just require Qt >= 5.2 to build?

**Comment by zaps166** [comment]
Ok, so it is a bug, I must add additional #ifdef for Qt 5.1
I'll do it later.

**Comment by DAP-DarkneSS** [comment]
OK, thanks.

**Comment by zaps166** [comment]
Please try again! (b78da01)

**Comment by DAP-DarkneSS** [comment]
Was built now, thank you!

**Comment by zaps166** [comment]
Ok, but remember that building with Qt4 provides more stable application!

**Comment by DAP-DarkneSS** [comment]
I package both Qt4 and Qt5 builds. Users could choose any they like.

**Comment by zaps166** [comment]
Ok :) !
QMPlay2 in openSUSE "multimedia:apps" - is it your package?
I found that ffmpeg from "multimedia:apps" doesn't support AAC decoding - why :D ?

**Comment by DAP-DarkneSS** [comment]
Yep, there is Qt5 build and packman provide Qt4 one. Imho openSUSE  
out-of-box ffmpeg is sick because of licensing problems.

**Comment by zaps166** [comment]
Ok, but FFmpeg AAC decoder is under LGPL license like Vorbis. Compiling FFmpeg without any flag enables AAC decoder.

Personally I like Vorbis and Opus, but AAC is very popular codec used also by YouTube, so is there any sense to provide FFmpeg without main codecs? Some people without knowledge of licenses will install FFmpeg from "multimedia" repository and there will be no sound e.g. on YouTube...

**Comment by DAP-DarkneSS** [comment]
Not code but technology/container licensing…

**Comment by zaps166** [comment]
So OK, and what about H.264?
I must implement merging audio stream (Opus/Vorbis) with video stream on YouTube and in multimedia repository it will also works OK :D
Thanks for packaging QMPlay2!

**Comment by DAP-DarkneSS** [comment]
Sorry, I have only very general information. The was no ffmpeg at all a  
year ago…

**Comment by zaps166** [comment]
Hi again!
I released new version - bugfixes. I noticed than new QMPlay2 doesn't use libsidplayfp and libgme on openSUSE. You must install devel files for them before compiling. I also created new mime-types for some file types: https://github.com/zaps166/QMPlay2/tree/master/src/gui/Unix , so they can be copied into /usr/share/mime/packages.

**Comment by DAP-DarkneSS** [comment]
> I noticed than new QMPlay2 doesn't use libsidplayfp and libgme on  
> openSUSE. You must install devel files for them before compiling.

Done, thanks.

> I also created new mime-types for some file types:  
> https://github.com/zaps166/QMPlay2/tree/master/src/gui/Unix , so they  
> can be copied into /usr/share/mime/packages.

And the didn't :) but I'm ready!
