### ISSUE TITLE
QMPlay2 21.12.24 fails to build on openSUSE Leap 15.3

### ISSUE THREAD

**Issue by DarkWav** [zaps166/QMPlay2#475]
Hello, I tried to build QMPlay2 `21.12.24` on openSUSE Leap 15.3 and the following error ocurred:
```
[  168s] FAILED: src/modules/PipeWire/CMakeFiles/PipeWire.dir/PipeWireWriter.cpp.o 
[  168s] /usr/bin/g++-10  -DNOMINMAX -DPipeWire_EXPORTS -DQMVK_WAIT_TIMEOUT_MS=2500 -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_USE_FAST_OPERATOR_PLUS -DQT_WIDGETS_LIB -DUSE_OPENGL -DUSE_VULKAN -DUSE_YOUTUBEDL -DVK_NO_PROTOTYPES -DVULKAN_HPP_TYPESAFE_CONVERSION -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -Isrc/modules/PipeWire -I../src/modules/PipeWire -Isrc/modules/PipeWire/PipeWire_autogen/include -I/usr/include/pipewire-0.3 -I/usr/include/spa-0.2 -I../src/qmplay2 -I/usr/include/ffmpeg -I../src/qmplay2/vulkan/headers/include -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtCore -isystem /usr/lib64/qt5/mkspecs/linux-g++ -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtSvg -Wall -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -DNDEBUG -O2 -g -DNDEBUG -fPIC   -fPIC -std=gnu++14 -Winvalid-pch -include /home/abuild/rpmbuild/BUILD/QMPlay2-src-21.12.24/build/src/modules/PipeWire/CMakeFiles/PipeWire.dir/cmake_pch.hxx -MD -MT src/modules/PipeWire/CMakeFiles/PipeWire.dir/PipeWireWriter.cpp.o -MF src/modules/PipeWire/CMakeFiles/PipeWire.dir/PipeWireWriter.cpp.o.d -o src/modules/PipeWire/CMakeFiles/PipeWire.dir/PipeWireWriter.cpp.o -c ../src/modules/PipeWire/PipeWireWriter.cpp
[  168s] ../src/modules/PipeWire/PipeWireWriter.cpp: In member function 'void PipeWireWriter::recreateStream()':
[  168s] ../src/modules/PipeWire/PipeWireWriter.cpp:388:31: error: 'PW_KEY_NODE_RATE' was not declared in this scope; did you mean 'PW_KEY_NODE_NAME'?
[  168s]   388 |     pw_properties_setf(props, PW_KEY_NODE_RATE, "1/%u", m_rate);
[  168s]       |                               ^~~~~~~~~~~~~~~~
[  168s]       |                               PW_KEY_NODE_NAME
```
I suspect this is due to the old `libpipewire-0.3` version openSUSE Leap 15.3 is working since compilation works just fine on openSUSE Leap 15.4+ and Tumbleweed. TW uses version `0.3.42`, Leap 15.4 uses version `0.3.39` and Leap 15.3 uses version `0.3.24`, so I suspect QMPlay2 `21.12.24` depends on some change in `libpipewire-0.3` that happened between versions `0.3.24` and `0.3.39`.

The error is probably caused by commit ea743c55cca384d2a8221591386071f03983bfbf, so since `PW_KEY_NODE_RATE` doesn't seem to be present in `libpipewire-0.3` version `0.3.24` should I just revert that specific commit for Leap 15.3 via a patch or is there an easy code fix?

**Comment by zaps166** [comment]
Yes, you can revert it or set `"node.rate"` directly instead of using not existing define.

**Comment by DarkWav** [comment]
> Yes, you can revert it or set `"node.rate"` directly instead of using not existing define.
Thanks, I think I'll make a patch for Leap 15.3 then.

**Comment by zaps166** [comment]
Maybe compile define with `#if` for PW API version check could be good, but I need to check which version added this.

**Comment by zaps166** [comment]
I fixed this issue on master branch.

**Comment by DarkWav** [comment]
Thanks!
