### ISSUE TITLE
Version 22.10.23 does not compile with Qt5 older than 5.15

### ISSUE THREAD

**Issue by fatabbot** [zaps166/QMPlay2#547]
I tried to compile Version 22.10.23 for Ubuntu packages. For ubuntu 22.04 and 22.10 there were no problems, ubuntu 20.04 stops to compile with `/<<PKGBUILDDIR>>/src/qmplay2/QMPlay2Core.cpp: In member function ‘void QMPlay2CoreClass::setLanguage()’:
/<<PKGBUILDDIR>>/src/qmplay2/QMPlay2Core.cpp:590:38: error: ‘class QTranslator’ has no member named ‘filePath’
  590 |         lang = QFileInfo(translator->filePath()).baseName();`

Well, the documentation https://doc.qt.io/qt-5/qtranslator.html#filePath says "This function was introduced in Qt 5.15." so this does not compile with Qt5.12.8 from 20.04 (your description says Qt5 >=5.10 is needed).

As workaround i patched the QMPlay2Core.cpp via debian/patches back to commit 51c935a728d672b2c89daee139d65a5e3639bfb6 so it does compile for Qt5.12.8.

**Comment by zaps166** [comment]
Hi, thanks, fixed!
You can use this 1ad1995dd0fb87ed0966b58be283b34db48c7425 !

**Comment by fatabbot** [comment]
Thanks a lot, will do so.
